# Generated by Django 5.2.15 on 2026-07-26 12:56

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0002_category"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="category",
            options={
                "ordering": ["name"],
                "verbose_name": "Family Head",
                "verbose_name_plural": "Family Heads",
            },
        ),
        migrations.AlterField(
            model_name="category",
            name="description",
            field=models.TextField(
                blank=True, help_text="Optional notes about this family group."
            ),
        ),
        migrations.AlterField(
            model_name="category",
            name="kind",
            field=models.CharField(
                choices=[
                    ("family", "Family Head"),
                    ("document", "Document"),
                    ("general", "General"),
                ],
                default="family",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="category",
            name="name",
            field=models.CharField(
                help_text="Family head name (e.g. each brother's name as head of their family).",
                max_length=120,
                unique=True,
            ),
        ),
    ]
