# Generated by Django 5.2.15 on 2026-07-26 12:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0002_customuser_category"),
        ("core", "0003_family_head_labels"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customuser",
            name="category",
            field=models.ForeignKey(
                blank=True,
                help_text="Select the family head this member belongs to.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="users",
                to="core.category",
                verbose_name="Family Head",
            ),
        ),
    ]
