# Generated by Django 5.2.16 on 2026-07-26 11:09

import django.db.models.deletion
import documents.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("families", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Document",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "doc_type",
                    models.CharField(
                        choices=[
                            ("national_id", "National ID"),
                            ("birth_certificate", "Birth Certificate"),
                            ("passport", "Passport"),
                            ("marriage_certificate", "Marriage Certificate"),
                            ("education_certificate", "Education Certificate"),
                            ("medical_report", "Medical Report"),
                            ("family_photo", "Family Photo"),
                            ("other", "Other / PDF"),
                        ],
                        default="other",
                        max_length=40,
                    ),
                ),
                ("title", models.CharField(blank=True, max_length=150)),
                (
                    "file",
                    models.FileField(
                        upload_to="documents/%Y/%m/",
                        validators=[documents.models.validate_upload],
                    ),
                ),
                ("uploaded_at", models.DateTimeField(auto_now_add=True)),
                (
                    "profile",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="documents",
                        to="families.familyprofile",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="documents",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-uploaded_at"],
            },
        ),
    ]
