# Generated by Django 5.2.17 on 2026-08-08 10:39

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("families", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="FamilyMember",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_deleted", models.BooleanField(db_index=True, default=False)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("full_name", models.CharField(max_length=255)),
                (
                    "profile_photo",
                    models.ImageField(blank=True, null=True, upload_to="members/"),
                ),
                (
                    "gender",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("male", "Male"),
                            ("female", "Female"),
                            ("other", "Other"),
                        ],
                        max_length=20,
                    ),
                ),
                ("date_of_birth", models.DateField(blank=True, null=True)),
                ("phone", models.CharField(blank=True, max_length=50)),
                ("email", models.EmailField(blank=True, max_length=254)),
                ("occupation", models.CharField(blank=True, max_length=150)),
                ("education", models.CharField(blank=True, max_length=150)),
                ("city", models.CharField(blank=True, max_length=100)),
                ("country", models.CharField(blank=True, max_length=100)),
                (
                    "marital_status",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("single", "Single"),
                            ("married", "Married"),
                            ("divorced", "Divorced"),
                            ("widowed", "Widowed"),
                            ("other", "Other"),
                        ],
                        max_length=20,
                    ),
                ),
                ("blood_type", models.CharField(blank=True, max_length=10)),
                ("emergency_contact", models.CharField(blank=True, max_length=255)),
                ("biography", models.TextField(blank=True)),
                ("joined_date", models.DateField(blank=True, null=True)),
                (
                    "family_role",
                    models.CharField(
                        choices=[
                            ("father", "Father"),
                            ("mother", "Mother"),
                            ("son", "Son"),
                            ("daughter", "Daughter"),
                            ("grandfather", "Grandfather"),
                            ("grandmother", "Grandmother"),
                            ("uncle", "Uncle"),
                            ("aunt", "Aunt"),
                            ("cousin", "Cousin"),
                            ("guardian", "Guardian"),
                            ("other", "Other"),
                        ],
                        default="other",
                        max_length=30,
                    ),
                ),
                ("is_archived", models.BooleanField(default=False)),
                (
                    "family",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="members",
                        to="families.family",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="member_profiles",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["full_name"],
            },
        ),
        migrations.CreateModel(
            name="Relationship",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "relation_type",
                    models.CharField(
                        choices=[
                            ("parent", "Parent"),
                            ("child", "Child"),
                            ("spouse", "Spouse"),
                            ("sibling", "Sibling"),
                            ("grandparent", "Grandparent"),
                            ("grandchild", "Grandchild"),
                            ("uncle_aunt", "Uncle/Aunt"),
                            ("niece_nephew", "Niece/Nephew"),
                            ("cousin", "Cousin"),
                            ("guardian", "Guardian"),
                            ("other", "Other"),
                        ],
                        max_length=30,
                    ),
                ),
                ("notes", models.CharField(blank=True, max_length=255)),
                (
                    "family",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="relationships",
                        to="families.family",
                    ),
                ),
                (
                    "from_member",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="relationships_from",
                        to="members.familymember",
                    ),
                ),
                (
                    "to_member",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="relationships_to",
                        to="members.familymember",
                    ),
                ),
            ],
        ),
        migrations.AddIndex(
            model_name="familymember",
            index=models.Index(
                fields=["family", "is_archived"], name="members_fam_family__1a23d5_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="familymember",
            index=models.Index(
                fields=["family", "family_role"], name="members_fam_family__702f5e_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="relationship",
            unique_together={("from_member", "to_member", "relation_type")},
        ),
    ]
